routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/templates/home');
});

Route::resource('/users','userController');
Route::resource('/categories','categoryController');
Route::resource('/books','bookController');
Route::resource('/orders','orderController');

Route::get('/users/search/email', 'userController@search')->name('users.search');
Route::get('/books/search/title', 'bookController@search')->name('books.search');
Route::get('/categories/search/category', 'categoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'orderController@search')->name('orders.search');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'title', 'description', 'author', 'publisher', 'cover', 'price', 'stock'
    ];

    public function category() {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/bookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Category;
use App\Books_Categories;

class bookController extends Controller
{
    public function index()
    {
        $books = Book::paginate(5);
        return view('books.index', compact('books'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('books.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $request->validate([
          'title' => 'required',
          'description' => 'required|max:200',
          'author' => 'required',
          'publisher' => 'required',
          'price' => 'required|numeric|max:999999',
          'stock' => 'required|numeric',
          'category'=> 'required',
          'cover' => 'image',
        ]);

        $new_book = new Book();
        $new_book->title = $request->get('title');
        $new_book->description = $request->get('description');
        $new_book->author = $request->get('author');
        $new_book->publisher = $request->get('publisher');
        $new_book->price = $request->get('price');
        $new_book->stock = $request->get('stock');
        if ($request->file('cover')) {
            $file = $request->file('cover')->store('cover','public');
            $new_book->cover = $file;
        }
        $new_book->save();

        $new_book->category()->attach($request->get('category'));

        return redirect()->route('books.index')->with('status','Book succesfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::findOrFail($id);
        return view('books.show',['book'=>$book]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        $categories = Category::all();
        return view('books.edit',['book'=>$book, 'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
          'title' => 'required',
          'description' => 'required|max:200',
          'author' => 'required',
          'publisher' => 'required',
          'price' => 'required|numeric|max:999999',
          'stock' => 'required|numeric',
          'category'=> 'required',
        ]);

        $update_book = Book::findOrFail($id);
        $update_book->title = $request->get('title');
        $update_book->description = $request->get('description');
        $update_book->author = $request->get('author');
        $update_book->publisher = $request->get('publisher');
        $update_book->price = $request->get('price');
        $update_book->stock = $request->get('stock');
        if ($request->file('cover')) {
            if ($update_book->cover && file_exists(storage_path('storage/'.$update_book->cover))) {
                Storage::delete('storage/'.$update_book->cover);
            }
            $file = $request->file('cover')->store('cover','public');
            $update_book->cover = $file;
        }
        $update_book->save();

        $update_book->category()->sync($request->get('category'));

        return redirect()->route('books.index',['id'=>$id])->with('status','Book succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
         $book = Book::findOrFail($id);
         if ($book->cover && file_exists(storage_path('public/storage/'.$book->cover))) {
             Storage::delete('public/storage/'.$book->cover);
         }
         $book->delete();
         return redirect()->route('books.index')->with('status', 'Book Successfully deleted');
     }

     public function search(Request $request)
     {
         $books = Book::when($request->found, function ($query) use ($request) {
             $query->where('title', 'like', "%{$request->found}%");
             // orWhere('description', 'like', "%{$request->found}%");
         })->paginate(5);

         $books->appends($request->only('found'));

         return view('books.index', compact('books'));
     }
}

resources/views/books/create.blade.php
@extends('templates.home')
@section('title')
    Create Books
@endsection
@section('content')
    <div class="container" >
      <br><br>
        <h3>Create Books</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Books</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="title" >Title</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="title" id="title">
                                {{ ($errors->has('title')) ? $errors->first('title') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="author">Author</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="author" id="author">
                                {{ ($errors->has('author')) ? $errors->first('author') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="publisher">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="publisher" id="publisher">
<<<<<<< HEAD
=======
                                {{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="price">Price</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="price" id="price">
                                {{ ($errors->has('price')) ? $errors->first('price') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stock">Stock</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="stock" id="stock">
                                {{ ($errors->has('stock')) ? $errors->first('stock') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="deskripsi">Deskripsi</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <textarea class="form-control" name="deskripsi" id="deskripsi" rows="6" >
                                </textarea>
=======
                                <textarea class="form-control" name="description" id="deskripsi" rows="6" >

                                </textarea>
                                {{ ($errors->has('description')) ? $errors->first('description') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="category">Category</label>
                            </div>
                            <div class="col-md-8">
                                <select multiple='multiple' name="category[]" id="category" class="form-control {{$errors->first('category') ? "is-invalid": ""}}">
                                    <option value="">Select Category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->cat_name }}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    {{$errors->first('category')}}
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
              						<div class="input-group mb-3">
              							<div class="col-md-3 text-primary">
              								Cover
              							</div>

              							<div class="col-md-8">
              								<div class="custom-file">
                									<input type="file" class="custom-file-input" name="cover" id="newAvatar">
                									<label class="custom-file-label" for="newAvatar">Upload Cover</label>
              									  {{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
              								</div>
              							</div>
              						</div>
              					</div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Book
@endsection
@section('content')
    <div class="container" >
        <h3>Form Edit Book</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $book['title'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('books.update',$book['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        @csrf
                        @method('PUT')
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="title">Title</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="title" id="title" value=" {{ $book['title'] }}">
                                {{ ($errors->has('title')) ? $errors->first('title') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="author">Author</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="author" id="author" value=" {{ $book['author'] }}">
                                {{ ($errors->has('author')) ? $errors->first('author') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="publisher">Publisher</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="publisher" id="publisher" value="{{ $book['publisher'] }}">
                                {{ ($errors->has('publisher')) ? $errors->first('publisher') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="price">Price</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="price" id="price" value=" {{ $book['price'] }}">
                                {{ ($errors->has('price')) ? $errors->first('price') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="stock">Stock</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="stock" id="stock" value="{{ $book['stock'] }}">
                                {{ ($errors->has('stock')) ? $errors->first('stock') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="deskripsi">Deskripsi</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <textarea class="form-control" name="deskripsi" id="deskripsi" rows="6">
                                    <?php echo $books['deskripsi'] ?>
                                </textarea>
=======
                                <textarea class="form-control" name="description" id="deskripsi" rows="6">
                                    {{ $book['description'] }}
                                </textarea>
                                {{ ($errors->has('description')) ? $errors->first('description') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="category">Category</label>
                            </div>
                            <div class="col-md-8">
                              @foreach($book->category as $category)
                                  <span class="badge badge-primary">{{ $category->cat_name }}  </span>
                              @endforeach
                                <select multiple='multiple' name="category[]" id="category" class="form-control {{$errors->first('category') ? "is-invalid": ""}}">
                                    <option value="">Select Category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->cat_name }}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    {{$errors->first('category')}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
              						<div class="input-group mb-3">
              							<div class="col-md-3 text-primary">
              								Cover
              							</div>

              							<div class="col-md-8">
              								<img src=" {{ asset('storage/'.$book['cover']) }} " alt="gambar" class="img-thumbnail" height="150px" width="150px">
              								<div class="custom-file">
                									<input type="file" class="custom-file-input" name="cover" id="newAvatar">
                									<label class="custom-file-label" for="newAvatar">Upload Cover</label>
              									  {{ ($errors->has('cover')) ? $errors->first('cover') : "" }}
              								</div>
              							</div>
              						</div>
              					</div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/index.blade.php
@extends('templates.home')
@section('title')
    List of Books
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>List of Books</h3>
        <hr>

        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-outline-primary " href="{{ route('books.create') }}">
                    <span data-feather="plus-circle"></span>
                    Create a new book <span class="sr-only">(current)</span>
                </a>
            </div>
            <div class="col-md-8">
          			<form action="{{ route('books.search') }}" class="form-inline" method="GET">
          			    <div class="form-group mx-sm-3 mb-2">
          			         <input class="form-control" name="found" placeholder="Search by Title..." value="{{ old('found') }}" style="width: 550px;">
          			    </div>
          			    <button class="btn btn-primary mb-2" type="submit">Search</button>
          			</form>
      			</div>
        </div>
        <br>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">No</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Publisher</th>
                        <th scope="col">Cover</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($books as $book)
                    <?php $no++; ?>
                        <tr>
                            <td>{{ $no }}</td>
                            <td>{{ $book['title'] }}</td>
                            <td>{{ $book['author'] }}</td>
                            <td>{{ $book['publisher'] }}</td>
                            <td> <img src="{{ 'storage/'.$book['cover'] }}" alt="" width="100px" height="100px"> </td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('books.show',$book['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('books.edit',$book['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this book permanently?')"
                                    action="{{route('books.destroy', $book['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="" style="margin: auto; width: 150px;">
                {{ $books->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/books/show.blade.php
@extends('templates.home')
@section('title')
    Detail of Book
@endsection
@section('content')
    <h1>Detail of Book </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:400px;">
        <div class="row " style="padding:25px">
            <div class="col-md-2 offset-md-5 offset-sm-4">
                <img src="{{ asset('storage/'.$book['cover']) }}" style="height:150px; width:150px; color:black;" class="rounded-circle" alt="img">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>{{ $book['title'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Author
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['author'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Publisher
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $book['publisher'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Price
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['price'] }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Stock
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['stock'] }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Description
            </div>
            <div class="col-md-4 col-sm-4 ">
                {{ $book['description'] }}
            </div>
        </div>
        <div class="row">
    			<div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
    				Category
    			</div>
    			<div class="col-md-4 col-sm-4">
    				<ul>
    				@foreach ($book->category as $categories)
    					   <li>{{ $categories->cat_name }}</li>
    				@endforeach
    				</ul>
    			</div>
    		</div>
    </div>
@endsection