routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/templates/home');
});

Route::resource('/users','userController');
Route::resource('/categories','categoryController');
Route::resource('/books','bookController');
Route::resource('/orders','orderController');

Route::get('/users/search/email', 'userController@search')->name('users.search');
Route::get('/books/search/title', 'bookController@search')->name('books.search');
Route::get('/categories/search/category', 'categoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'orderController@search')->name('orders.search');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'cat_name','desc'
    ];

    public function book() {
        return $this->belongsToMany(Book::class);
    }
}

app/Http/Controllers/categoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class categoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $categories = Category::paginate(5);
        return view('category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
<<<<<<< HEAD
      echo "Anda Berada pada method Store pada categoryController ";
      return $request;
=======
        $request->validate([
            'cat_name' => 'required|unique:categories',
            'desc' => 'required|max:200',
        ]);
        $new_cat = new Category();
        $new_cat->cat_name = $request->get('cat_name');
        $new_cat->desc = $request->get('desc');
        $new_cat->save();
        return redirect()->route('categories.index')->with('status','Category Succesfully Created');
>>>>>>> SUBMISSION_3
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('category.show',['category'=>$category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit',['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'cat_name' => 'required',
            'desc' => 'required|max:200',
        ]);
        $update_cat = Category::findOrFail($id);
        $update_cat->cat_name = $request->get('cat_name');
        $update_cat->desc = $request->get('desc');
        $update_cat->save();
        return redirect()->route('categories.index',['id'=>$id])->with('status','Category succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
         $category = Category::findOrFail($id);
         $category->delete();
         return redirect()->route('categories.index')->with('status', 'Category Successfully deleted');
     }

     public function search(Request $request)
     {

         $categories = Category::when($request->found, function ($query) use ($request) {
            $query->where('cat_name', 'like', "%{$request->found}%");
         })->paginate(5);
         return view('category.index', compact('categories'));
     }
}

resources/views/category/create.blade.php
@extends('templates.home')
@section('title')
    Create Category
@endsection
@section('content')
    <div class="container" ><br><br>
        <h3>Create Category</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Category</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('categories.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="cat_name" >Category Name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="cat_name" id="cat_name">
                                {{ ($errors->has('cat_name')) ? $errors->first('cat_name') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="desc" class="text-primary">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea name="desc" id="desc" rows="5" cols="58"></textarea>
                                {{ ($errors->has('desc')) ? $errors->first('desc') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Category
@endsection
@section('content')
    <div class="container" >
      <br><br>
        <h3>Form Edit Category</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $category['cat_name'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('categories.update',$category['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">
                             @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="cat_name" class="text-primary">Category Name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="cat_name" id="cat_name" value="{{ $category['cat_name'] }}">
                                {{ ($errors->has('cat_name')) ? $errors->first('cat_name') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="desc" class="text-primary">Description</label>
                            </div>
                            <div class="col-md-8">
                                <textarea name="desc" id="desc" rows="5" cols="56" style="padding: 3px 10px;">{{ $category['desc'] }}</textarea>
                                {{ ($errors->has('desc')) ? $errors->first('desc') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('templates.home')
@section('title')
    List of Categories
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>List of Categories</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-outline-primary " href="{{ route('categories.create') }}">
                    <span data-feather="plus-circle"></span>
                    Create a new category <span class="sr-only">(current)</span>
                </a>
            </div>
            <div class="col-md-8">
          			<form action="{{ route('categories.search') }}" class="form-inline" method="GET">
          			    <div class="form-group mx-sm-3 mb-2">
          			         <input class="form-control" name="found" placeholder="Search by name..." value="{{ old('found') }}" style="width: 550px;">
          			    </div>
          			    <button class="btn btn-primary mb-2" type="submit">Search</button>
          			</form>
      			</div>
        </div>
        <br>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">No</th>
                        <th scope="col">Category Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                    <?php $no++; ?>
                        <tr>
                            <td>{{ $no }}</td>
                            <td>{{ $category['cat_name'] }}</td>
                            <td>{{ $category['desc'] }}</td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('categories.show',$category['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('categories.edit',$category['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this Category permanently?')"
                                    action="{{route('categories.destroy', $category['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="" style="width:150px; margin: auto;">
            {{ $categories->links() }}
        </div>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('templates.home')
@section('title')
    Detail of Category
@endsection
@section('content')
<br><br>
    <h1>Detail of Category </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:400px;">
        <div class="row " style="padding:25px">
            <div class="col-md-12 text-center">
                <h3>{{ $category['cat_name'] }}</h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                ID
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $category['id'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Description
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $category['desc'] }}
            </div>
            <br>
        </div>
    </div>
@endsection