routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/templates/home');
});

Route::resource('/users','userController');
Route::resource('/categories','categoryController');
Route::resource('/books','bookController');
Route::resource('/orders','orderController');

Route::get('/users/search/email', 'userController@search')->name('users.search');
Route::get('/books/search/title', 'bookController@search')->name('books.search');
Route::get('/categories/search/category', 'categoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'orderController@search')->name('orders.search');

resources/views/templates/partials/_head.blade.php
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<title>@yield('title')</title>
	<link href="{{asset('css/app.css')}}" rel="stylesheet">
	<link href="{{asset('css/dashboard.css')}}" rel="stylesheet">
	@yield('css')
</head>

resources/views/templates/partials/_script.blade.php
<script src="{{asset('js/app.js')}}"></script>
<script src="{{asset('js/feather.min.js')}}"></script>
<script> feather.replace() </script>
@yield('js')

resources/views/templates/partials/_sideNav.blade.php
<nav class="col-md-2 d-none d-md-block bg-dark sidebar">
	<div class="sidebar-sticky">
		<ul class="nav flex-column">
			<li class="nav-item ">
				<a class="nav-link active" href="{{ route('users.index') }}">
					<span data-feather="users"></span>Users<br>
				</a>
				<a  class="nav-link active" href="{{ route('books.index') }}">
					<span data-feather="book"></span>Books<br>
				</a>
				<a  class="nav-link active" href="{{ route('categories.index') }}">
					<span data-feather="list"></span>Categories<br>
				</a>
				<a  class="nav-link active" href="{{ route('orders.index') }}">
					<span data-feather="shopping-cart"></span>Orders<br>
				</a>
			</li>
		</ul>
	</div>
</nav>

resources/views/templates/partials/_topNav.blade.php
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-success flex-md-nowrap p-0 shadow">
	<a class="navbar-brand" href="#">notwo- shop</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" arialabel="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{{ route('users.index') }}">Users</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route('books.index') }}">Books</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route('categories.index') }}">Categories</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ route('orders.index') }}">Orders</a>
			</li>
		</ul>

		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="text" placeholder="Search" arialabel="Search">
			<button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
		</form>

		<ul class="navbar-nav px-3">
			<li class="nav item dropdown">
			 	<a class="nav-link dropdown-toggle" href="#" id="dropdown01" datatoggle="dropdown" aria-haspopup="true" aria-expanded="false">Username</a>
			 	<div class="dropdown-menu" aria-labelledby="dropdown01">
			 		<a class="dropdown-item" href="#">Logout</a>
			 	</div>
			</li>
		</ul>
	</div>
</nav>