routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/templates/home');
});

Route::resource('/users','userController');
Route::resource('/categories','categoryController');
Route::resource('/books','bookController');
Route::resource('/orders','orderController');

Route::get('/users/search/email', 'userController@search')->name('users.search');
Route::get('/books/search/title', 'bookController@search')->name('books.search');
Route::get('/categories/search/category', 'categoryController@search')->name('categories.search');
Route::get('/orders/search/pesanan', 'orderController@search')->name('orders.search');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Order extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'user_id', 'tot_har', 'inv_no', 'status'
    ];

    public function users() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/orderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\User;

class orderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::paginate(5);
        return view('orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('orders.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'user_id' => 'required',
            'inv_no' => 'required|min:5|max:20',
            'tot_har' => 'required|numeric',
            'status'=> 'required'
        ]);
        $new_order = new Order();
        $new_order->user_id = $request->get('user_id');
        $new_order->inv_no = $request->get('inv_no');
        $new_order->tot_har = $request->get('tot_har');
        $new_order->status = $request->get('status');
        $new_order->save();

        return redirect()->route('orders.index')->with('status','Order Succesfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::with('users')->find($id);
        return view('orders.show',['order'=>$order]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::with('users')->find($id);
        $users = User::all();
        return view('orders.edit',['order'=>$order], compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
          'inv_no' => 'required|min:5|max:30',
          'user_id' => 'required',
          'tot_har' => 'required|numeric',
          'status'=> 'required'
      ]);
      $update_order = Order::findOrFail($id);
      $update_order->inv_no = $request->get('inv_no');
      $update_order->user_id = $request->get('user_id');
      $update_order->tot_har = $request->get('tot_har');
      $update_order->status = $request->get('status');
      $update_order->save();
      return redirect()->route('orders.index')->with('status','Order Succesfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     {
         $order = Order::findOrFail($id);
         $order->delete();
         return redirect()->route('orders.index')->with('status', 'Order Successfully deleted');
     }

     public function search(Request $request)
     {
         $orders = Order::when($request->found, function ($query) use ($request) {
           $query->where('inv_no', 'like', "%{$request->found}%")->
           where('status', 'like', "%{$request->statuss}%");
         })->paginate(5);
         return view('orders.index', compact('orders'));
     }
}

resources/views/orders/create.blade.php
@extends('templates.home')
@section('title')
    Create Order
@endsection
@section('content')
    <div class="container" >
      <br><br>
        <h3>Create Order</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5> Create a New Order</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('orders.store') }}" class="form-group" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row" >
                            <div class="col-md-3">
                                <label for="inv_no" >Invoice Number</label>
                            </div>
                            <div class="col-md-8">
                                <input type="number" class="form-control" name="inv_no" id="inv_no">
<<<<<<< HEAD
=======
                                {{ ($errors->has('inv_no')) ? $errors->first('inv_no') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="tot_har">Total Price</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <input type="number" class="form-control" name="jumlah" id="jumlah">
=======
                                <input type="number" class="form-control" name="tot_har" id="tot_har">
                                {{ ($errors->has('tot_har')) ? $errors->first('tot_har') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="user_id">User</label>
                            </div>
                            <div class="col-md-8">
                                <select name="user_id" id="user_id" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
                                    <option value="">Select User</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                {{ ($errors->has('user_id')) ? $errors->first('user_id') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="status">Status</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <input type="text" class="form-control" name="Status" id="Status">
=======
                                <select name="status" id="status" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
                                    <option value="">Select Status</option>
                                    <option value="SUBMIT">SUBMIT</option>
                                    <option value="PROCESS">PROCESS</option>
                                    <option value="FINISH">FINISH</option>
                                    <option value="CANCEL">CANCEL</option>
                                </select>
                                {{ ($errors->has('status')) ? $errors->first('status') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/edit.blade.php
@extends('templates.home')
@section('title')
    Edit Order
@endsection
@section('content')
    <div class="container" ><br><br>
        <h3>Form Edit Order</h3>
        <hr>
        <div class="card border-primary" style="max-width: 70%; margin:auto; margin-top:40px;">
            <div class="card-header bg-primary text-white">
                <h5>{{ $order['inv_no'] }}</h5>
            </div>
            <div class="card-body">
                <div class="container text-primary">
                    <form action="{{ route('orders.update',$order['id']) }}" method="POST" class="form-group" enctype="multipart/form-data">                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <label for="inv_no">Invoice Number</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <input type="text" class="form-control" name="jumlah" id="jumlah" placeholder="{{ $orders['jumlah'] }}">
                                 <input type="hidden" class="form-control" name="jumlah" id="jumlah" value="{{ $orders['jumlah'] }}">
=======
                              <input type="number" class="form-control" name="inv_no" id="inv_no" value="{{ $order['inv_no'] }}">
                              {{ ($errors->has('inv_no')) ? $errors->first('inv_no') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="tot_har">Total Harga</label>
                            </div>
                            <div class="col-md-8">
<<<<<<< HEAD
                                <input type="number" class="form-control" name="tot_har" id="tot_har" placeholder="{{ $orders['tot_har'] }}">
                                <input type="hidden" class="form-control" name="tot_har" id="tot_har" value="{{ $orders['tot_har'] }}">

=======
                                <input type="number" class="form-control" name="tot_har" id="tot_har" value="{{ $order['tot_har'] }}">
                                {{ ($errors->has('tot_har')) ? $errors->first('tot_har') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="user_id">User</label>
                            </div>
                            <div class="col-md-8">
                                <select name="user_id" id="user_id" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
                                    <option value="{{ $order->users->id }}">{{ $order->users->name }}</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                {{ ($errors->has('user_id')) ? $errors->first('user_id') : "" }}
>>>>>>> SUBMISSION_3
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3">
                                <label for="status">Status</label>
                            </div>
                            <div class="col-md-8">
                                <select name="status" id="status" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
                                    <option value="{{ $order['status'] }}" >{{ $order['status'] }}</option>
                                    <option value="SUBMIT">SUBMIT</option>
                                    <option value="PROCESS">PROCESS</option>
                                    <option value="FINISH">FINISH</option>
                                    <option value="CANCEL">CANCEL</option>
                                </select>
                                {{ ($errors->has('status')) ? $errors->first('status') : "" }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-3 offset-md-5 offset-sm-4">
                                <button type="submit" class="btn btn-outline-primary" >Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders/index.blade.php
@extends('templates.home')
@section('title')
    List of Orders
@endsection
@section('css')
    <style>
        body{
            padding-top: 30px;
        }
        th, td {
            padding: 10px;
            text-align: center;
        }
        td a{
            margin: 3px;
            align-content: center;
            color: white;
        }
        td a:hover{
            text-decoration: none;
        }
        td button{
            margin-top: 5px;
            cursor: pointer;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <h3>List of Orders</h3>
        <hr>
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('status') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-outline-primary " href="{{ route('orders.create') }}">
                    <span data-feather="plus-circle"></span>
                    Create a new order <span class="sr-only">(current)</span>
                </a>
            </div>
            <div class="col-md-8">
          			<form action="{{ route('orders.search') }}" class="form-inline" method="GET">
          			    <div class="form-group mx-sm-3 mb-2">
          			         <input class="form-control" name="found" placeholder="Search by Invoice Number..." value="{{ old('found') }}" style="width: 350px;">
          			    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <select name="statuss" id="status" class="form-control {{$errors->first('user_id') ? "is-invalid": ""}}">
                            <option value="">ANY</option>
                            <option value="SUBMIT">SUBMIT</option>
                            <option value="PROCESS">PROCESS</option>
                            <option value="FINISH">FINISH</option>
                            <option value="CANCEL">CANCEL</option>
                        </select>
                    </div>
          			    <button class="btn btn-primary mb-2" type="submit">Search</button>
          			</form>
      			</div>
        </div>
        <br>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">Id</th>
                        <th scope="col">Invoice Number</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($orders as $order)
                        <tr>
                            <td>{{ $order['id'] }}</td>
                            <td>{{ $order['inv_no'] }}</td>
                            <td>{{ $order->users->name }}</td>
                            <td>Rp. {{ $order['tot_har'] }}</td>
                            <td>
                                @if ( $order['status'] == "SUBMIT" )
                                    <span class="badge badge-warning"> {{ $order['status'] }} </span>
                                @elseif ( $order['status'] == "PROCESS" )
                                    <span class="badge badge-primary"> {{ $order['status'] }} </span>
                                @elseif ( $order['status'] == "FINISH" )
                                    <span class="badge badge-success"> {{ $order['status'] }} </span>
                                @else
                                    <span class="badge badge-danger"> {{ $order['status'] }} </span>
                                @endif
                            </td>
                            <td>
                                <a class="btn-sm btn-primary" href="{{ route('orders.show',$order['id']) }}">
                                <span data-feather="eye"></span>
                                Detail <span class="sr-only">(current)</span></a>
                                <a class="btn-sm btn-success d-inline" href="{{ route('orders.edit',$order['id']) }}">
                                <span data-feather="edit-2"></span>
                                Edit <span class="sr-only">(current)</span></a>
                                <form class="d-inline"
                                    onsubmit="return confirm('Delete this order permanently?')"
                                    action="{{route('orders.destroy', $order['id'])}}"
                                    method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-sm btn-danger" value="Delete">
                                    <span data-feather="trash"></span>
                                    Delete <span class="sr-only">(current)</span></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="" style="margin: auto; width:150px;">
                {{ $orders->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('templates.home')
@section('title')
    Detail of Order
@endsection
@section('content')
    <h1>Detail of Order </h1>
    <hr>
    <br>
    <div class="card bg-white border-info" style="max-width:70%; margin:auto; min-height:400px;">
        <div class="row">
            <div class="col-md-12 text-center">
              <br>
                <h3><strong>{{ $order['inv_no'] }}</strong></h3>
            </div>
        </div>
        <hr>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                User
            </div>
            <div class="col-md-4 col-sm-4">
                {{ $order->users->name }}
            </div>
            <br>
        </div>
        <br>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
                Total Harga
            </div>
            <div class="col-md-4 col-sm-4">
                Rp. {{ $order['tot_har'] }}
            </div>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2 col-sm-3 offset-sm-2">
              Status
            </div>
            <div class="col-md-4 col-sm-4 ">
                @if ( $order['status'] == "SUBMIT" )
                    <span class="badge badge-warning""> {{ $order['status'] }} </span>
                @elseif ( $order['status'] == "PROCESS" )
                    <span class="badge badge-primary""> {{ $order['status'] }} </span>
                @elseif ( $order['status'] == "FINISH" )
                    <span class="badge badge-success""> {{ $order['status'] }} </span>
                @else
                    <span class="badge badge-danger""> {{ $order['status'] }} </span>
                @endif
            </div>
        </div>

    </div>
@endsection